# CONFIGURATION OPTIONS FOR THE UNINACHT BUZZ-WIRE GAME

# mode that the game is run in (debug/release)
mode = "debug"

# timespan before the game times out
timeout = "20s"

# debouncing of the wire contact
debounceContact = "300ms"

# set the start number of ids
startNumber = "2"
